// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SysProg_OOP_HW003_WebShortCuts_r00.Models;

public partial class webtrack
{
    public int id { get; set; }

    public DateTime? date { get; set; }

    public TimeSpan? time { get; set; }

    public string url { get; set; }

    public string name { get; set; }

    public string owner { get; set; }
}